### ISSUE TITLE
Crop - add more aspect ratios

### ISSUE THREAD

**Issue by bokifogo** [Abizer-R/QuickEdit-Photo-Editor#23]
Hello, the app looks nice. It would be great if you could add more aspect ratios for cropping images, i.e. **9:20**, **9:19.5** etc.

**Comment by bokifogo** [comment]
> Hey man. I'll try to do add an option to choose a custom ratio, then you can choose any ratio you want. How does that sound?

That sounds great.

**Comment by xxxxme** [comment]
You could look at Simple Gallery https://github.com/SimpleMobileTools/Simple-Gallery for one way to do this.

**Comment by Abizer-R** [comment]
I've added option in Cropper where you can choose X and Y values for aspect ratio. It's live on Play Store
